### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by rainoftime** [Chilledheart/libch#2]
Any documentation:)?

**Comment by Chilledheart** [comment]
Document is not in plan yet. Which part of features do you want to explain about?

**Comment by rainoftime** [comment]
Build and usage 
- Win/Nix/..;  gcc/clang/...;  CMake/Makefile/scons...
- Features and examples.

**Comment by Chilledheart** [comment]
Yes, it could be part of this project if you want to open a PR for it.

**Comment by Chilledheart** [comment]
doxygen document is provided at http://blog.windyland.me/libch/html/annotated.html
